### ISSUE TITLE
Update Bookmark methods not working

### ISSUE THREAD

**Issue by Akamaozu** [robinjmurphy/node-readability-api#3]
First off, thanks for an awesome lib. Helped me fast-track a little project I was working on ([making an offline-capable webapp for Readability](https://github.com/Akamaozu/offline-readability)). 

**Everything worked perfectly til I tried to update the favorite or archive state of a bookmark.**

After some investigation, I discovered two separate issues keeping it from working.

**1. Bookmark status updates must be sent as a form submission.**
 See: https://www.readability.com/developers/api/reader#idm301959838128

**2. Favourites property for bookmark updates is spelled the americanized way: `favorites`.**
See above link.

I updated and tested it; works perfectly with very minor patches. I'm submitting pull requests to push the changes upstream.

:)

Once again, thanks for making my life easier. Just trying to make everyone else's just a little bit easier too.

**Comment by robinjmurphy** [comment]
Thanks for your PRs @Akamaozu. Should be fixed now in 1.0.0.
